import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Root } from '@adaptavant/eds-core'; // Adjust based on your library
import brand from "@adaptavant/eds-brands/setmore-black";
import translations from "@adaptavant/eds-translations/english";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Root
          className="h-[800px]"
          brand={brand}
          colorScheme="light"
          translations={translations}
        >
        {children}
        </Root>
      </body>
    </html>
  );
}
